#! /usr/local/bin/perl

use strict;
use warnings;

my($in);

my (%escape, $escapevals);

BEGIN {
    %escape = (
        "\\" => "\\\\",
        "\"" => "\\\"",
        "\r" => "\\r",
        "\n" => "\\n",
        "\t" => "\\t",
    );
    $escapevals = join("", values(%escape));
}

while (defined(my $line=<>)) {
    if ($line =~ /^\s*--\s*([_A-Za-z][_A-Za-z0-9]*)\s*$/) {
	if ($in) {
	    print ";\n\n";
	}
	print "static char const ",$1,"[] =";
	$in=1;
    } elsif ($in && $line =~ /\S/) {
	$line =~ s/([$escapevals]|[^ -~])/
		   $escape{$1} || sprintf("\\%.3o", ord($1))/ge;
	print "\n    \"",$line,"\"";
    }
}

if ($in) {
    print ";\n\n";
}

